#Reads filter parquet and creates Pres_Grid and splits — runs for atlantic, pacific, indian
#Needs files generated by 0.Dowload data script
import gc
import json
import os
import warnings
from collections import defaultdict
from pathlib import Path
from datetime import datetime
import numpy as np
import pandas as pd
import pyarrow.parquet as pq
import joblib

warnings.filterwarnings("ignore")


# PER-OCEAN CONFIG — edit paths here
OCEAN_CONFIGS = {
    "atlantic": {
        "parquet_path": "/work/drgarcia/Dataset/atlantic_ocean/2021-2025/1.processed/atlantic_2021_2025_clean2.parquet",
        "output_base":  "/work/drgarcia/Dataset/DL_datasets/atlantic_ocean/2021_2025",
    },
    "pacific": {
        "parquet_path": "/work/drgarcia/Dataset/pacific_ocean/2021-2025/1.processed/pacific_2021_2025_clean2.parquet",
        "output_base":  "/work/drgarcia/Dataset/DL_datasets/pacific_ocean/2021_2025",
    },
    "indian": {
        "parquet_path": "/work/drgarcia/Dataset/indian_ocean/2021-2025/1.processed/indian_2021_2025_clean2.parquet",
        "output_base":  "/work/drgarcia/Dataset/DL_datasets/indian_ocean/2021_2025",
    },
}

# Pipeline constants (shared across oceans)
CHUNK_SIZE = 500_000
MIN_LEVELS = 10
DATE_COL   = "JULD"
TRAIN_END  = pd.Timestamp("2024-01-01")
VAL_END    = pd.Timestamp("2025-01-01")

VARS_INTERES = [
    'DATA_TYPE', 'REFERENCE_DATE_TIME', 'DATE_CREATION', 'DATE_UPDATE',
    'PLATFORM_NUMBER', 'CYCLE_NUMBER', 'DIRECTION', 'DATA_CENTRE', 'DATA_MODE',
    'PLATFORM_TYPE', 'JULD', 'JULD_QC', 'JULD_LOCATION',
    'LATITUDE', 'LONGITUDE', 'POSITION_QC', 'PROFILE_PRES_QC',
    'PROFILE_TEMP_QC', 'PROFILE_PSAL_QC',
    'PRES', 'PRES_QC', 'PRES_ADJUSTED', 'PRES_ADJUSTED_QC', 'PRES_ADJUSTED_ERROR',
    'TEMP', 'TEMP_QC', 'TEMP_ADJUSTED', 'TEMP_ADJUSTED_QC', 'TEMP_ADJUSTED_ERROR',
    'PSAL', 'PSAL_QC', 'PSAL_ADJUSTED', 'PSAL_ADJUSTED_QC', 'PSAL_ADJUSTED_ERROR',
]

REQUIRED_COLS = [
    "PLATFORM_NUMBER", "CYCLE_NUMBER", "DIRECTION", "PRES", "TEMP", "PSAL",
    "PRES_QC", "TEMP_QC", "PSAL_QC", "JULD_QC", "JULD", "POSITION_QC",
    "LATITUDE", "LONGITUDE",
]

VALID_OBS_QC      = {1, 2, 3, 4}
VALID_JULD_QC     = {1, 2}
VALID_POSITION_QC = {1, 2}

PROFILE_KEY = ["PLATFORM_NUMBER", "CYCLE_NUMBER", "DIRECTION"]

OBS_QC_COLS = [
    "PRES_QC", "TEMP_QC", "PSAL_QC", "JULD_QC", "POSITION_QC",
    "PRES_ADJUSTED_QC", "TEMP_ADJUSTED_QC", "PSAL_ADJUSTED_QC",
]
PROFILE_QC_COLS = ["PROFILE_PRES_QC", "PROFILE_TEMP_QC", "PROFILE_PSAL_QC"]

SPLIT_MODE      = "time"
ASCENDING_ONLY  = True

# DATA_MODE: R=Real-Time, A=Adjusted, D=Delayed-Mode. Delayed-mode has been
# through manual QC review and is the most reliable -- this mirrors the
# DELAYED_MODE_ONLY flag in the tabular preprocess so both pipelines see the
# exact same population of rows. Keep it a flag (not hardcoded) so it's easy
# to toggle and compare.
DELAYED_MODE_ONLY = True

# POSITION_QC: quality flag of the profile position (LATITUDE/LONGITUDE).
# If True, keep only rows with POSITION_QC in {1, 2}. Mirrors the tabular
# preprocess's POSITION_QC_FILTER flag.
POSITION_QC_FILTER = True

GRID_LEN      = 100
GRID_MAX_PRES = 2000.0
PRESSURE_GRID = np.linspace(0.0, GRID_MAX_PRES, GRID_LEN).astype(np.float32)

# Coverage handling.
# MIN_COVERAGE is the threshold used either for reporting (default) or for
# an actual discard filter, depending on DISCARD_LOW_COVERAGE below.
#
# DISCARD_LOW_COVERAGE = False (default): profiles are NEVER dropped for low
# coverage. Every profile with >= MIN_LEVELS raw points is kept; grid
# positions outside its real pressure range are filled with 0 and flagged
# False in `mask`. This keeps the SAME population of profiles as the tabular
# pipeline (no depth-based sampling bias when comparing models). Downstream
# training/evaluation code MUST multiply the reconstruction loss by `mask`
# so filled positions never contribute.
#
# DISCARD_LOW_COVERAGE = True: reverts to the original behavior -- profiles
# covering less than MIN_COVERAGE of the grid are discarded outright. Left
# in place ("por si acaso") in case you want to reproduce that behavior or
# compare both settings, but it will make the CNN's profile population
# diverge from the tabular one (see compare_profile_sets.py).
MIN_COVERAGE          = 0.5
DISCARD_LOW_COVERAGE  = False

filter_juld_qc = (SPLIT_MODE == "time")
desc_tag   = "ascA" if ASCENDING_ONLY else "ascAD"
dmode_tag  = "_dmodeD" if DELAYED_MODE_ONLY else ""
cov_tag    = "_covfilt" if DISCARD_LOW_COVERAGE else "_masked"

QC_LETTER_DESC = {
    "A": "A (100% of profile levels good)",
    "B": "B (75% <= good < 100%)",
    "C": "C (50% <= good < 75%)",
    "D": "D (25% <= good < 50%)",
    "E": "E (0% < good < 25%)",
    "F": "F (0% good)",
}

# ENHANCED LOGGING & REPORTING

class FilterReport:
    """Track rows before/after each filter step with percentage information."""

    def __init__(self, stage_name: str, initial_count: int):
        self.stage_name = stage_name
        self.initial_count = initial_count
        self.current_count = initial_count
        self.steps = []

    def apply_filter(self, filter_name: str, new_count: int):
        """Record a filter application."""
        dropped = self.current_count - new_count
        pct_drop = (dropped / self.current_count * 100) if self.current_count > 0 else 0
        pct_remain = (new_count / self.initial_count * 100) if self.initial_count > 0 else 0

        self.steps.append({
            "filter": filter_name,
            "before": self.current_count,
            "after": new_count,
            "dropped": dropped,
            "pct_dropped": pct_drop,
            "pct_of_original": pct_remain,
        })
        self.current_count = new_count

    def print_summary(self):
        """Print a formatted summary of all filter steps."""
        print()
        print(f"FILTER SUMMARY: {self.stage_name}")
        print(f"{'Filter Step':<35} {'Before':>12} {'After':>12} {'Dropped':>12} {'% Lost':>8} {'% Total':>8}")
        print("-" * 90)

        for step in self.steps:
            print(f"{step['filter']:<35} {step['before']:>12,} {step['after']:>12,} "
                  f"{step['dropped']:>12,} {step['pct_dropped']:>7.1f}% {step['pct_of_original']:>7.1f}%")

        print("-" * 90)
        print(f"{'FINAL':<35} {self.initial_count:>12,} {self.current_count:>12,} "
              f"{self.initial_count - self.current_count:>12,} "
              f"{((self.initial_count - self.current_count) / self.initial_count * 100):>7.1f}% {'100.0%':>8}")
        print()


class FinalReport:
    """Consolidated final report with all key statistics in English."""

    def __init__(self):
        self.total_raw = 0
        self.total_cleaned = 0
        self.n_valid_profiles = 0
        self.split_stats = {}
        self.grid_stats = {}
        self.temporal_stats = {}
        self.platform_stats = {}
        self.anomaly_stats = {}

    def add_split_stats(self, split_name: str, n_profiles: int, n_anomalous: int,
                        n_unique_floats: int, date_min: str, date_max: str):
        """Add statistics for a split."""
        self.split_stats[split_name] = {
            "n_profiles": n_profiles,
            "n_anomalous": n_anomalous,
            "pct_anomalous": (n_anomalous / n_profiles * 100) if n_profiles > 0 else 0,
            "n_unique_floats": n_unique_floats,
            "date_min": date_min,
            "date_max": date_max,
        }

    def add_grid_stats(self, avg_coverage: float, n_skipped: int, orphan_profiles: int,
                       worst_levels: dict, n_low_coverage_kept: int = 0,
                       discard_low_coverage: bool = False):
        """Add grid interpolation statistics."""
        self.grid_stats = {
            "avg_coverage": avg_coverage,
            "n_skipped_low_coverage": n_skipped,
            "orphan_bad_profiles": orphan_profiles,
            "worst_covered_levels": worst_levels,
            "n_low_coverage_kept": n_low_coverage_kept,
            "discard_low_coverage": discard_low_coverage,
        }

    def add_temporal_stats(self, date_min: str, date_max: str, years: list,
                          months_covered: int):
        """Add temporal coverage information."""
        self.temporal_stats = {
            "date_range_min": date_min,
            "date_range_max": date_max,
            "years_included": years,
            "months_covered": months_covered,
        }

    def print_comprehensive_report(self, output_dir: str, grid_len: int,
                                   grid_max_pres: float, norm_stats: dict):
        """Print a comprehensive final report in English."""
        print()
        print("╔" + "=" * 108 + "╗")
        print("║" + " " * 35 + "FINAL PREPROCESSING REPORT" + " " * 47 + "║")
        print("╚" + "=" * 108 + "╝")
        print()

        # ---- DATA REDUCTION ----
        print(" DATA REDUCTION SUMMARY")
        print("  " + "-" * 106)
        print(f"    Raw observations (input)           : {self.total_raw:>20,}")
        print(f"    Observations after cleaning        : {self.total_cleaned:>20,}")
        print(f"    Observations discarded             : {self.total_raw - self.total_cleaned:>20,} "
              f"({(1 - self.total_cleaned/self.total_raw)*100:>5.1f}%)")
        print(f"    Valid profiles (gridded)           : {self.n_valid_profiles:>20,}")
        print()

        # ---- SPLITS ----
        print("  TRAIN/VAL/TEST SPLIT DISTRIBUTION")
        print("  " + "-" * 106)
        print(f"    {'Split':<15} {'Profiles':>15} {'Anomalous':>15} {'% Anomaly':>12} {'Unique Floats':>15} {'Date Range':<25}")
        print("    " + "-" * 104)

        for split_name in ["train", "val", "test"]:
            if split_name in self.split_stats:
                s = self.split_stats[split_name]
                date_range = f"{s['date_min']} → {s['date_max']}"
                print(f"    {split_name:<15} {s['n_profiles']:>15,} {s['n_anomalous']:>15,} "
                      f"{s['pct_anomalous']:>11.2f}% {s['n_unique_floats']:>15,} {date_range:<25}")
        print()

        # ---- GRID INTERPOLATION ----
        print("  GRID INTERPOLATION DIAGNOSTICS")
        print("  " + "-" * 106)
        print(f"    Grid resolution                    : {grid_len} levels, 0–{grid_max_pres:.0f} dbar")
        print(f"    Average profile coverage           : {self.grid_stats['avg_coverage']:>20.1%}")
        print(f"    Discard low-coverage filter        : {self.grid_stats['discard_low_coverage']:>20}")
        if self.grid_stats['discard_low_coverage']:
            print(f"    Profiles discarded (low coverage)  : {self.grid_stats['n_skipped_low_coverage']:>20,}")
        else:
            print(f"    Low-coverage profiles KEPT (masked): {self.grid_stats['n_low_coverage_kept']:>20,}")
        print(f"    Orphan bad profiles (grid QC loss) : {self.grid_stats['orphan_bad_profiles']:>20,}")
        if self.grid_stats['orphan_bad_profiles'] > 0:
            orphan_pct = self.grid_stats['orphan_bad_profiles'] / max(self.split_stats['train']['n_anomalous'] +
                                                                        self.split_stats['val']['n_anomalous'] +
                                                                        self.split_stats['test']['n_anomalous'], 1) * 100
            print(f"    └─ % of total anomalous profiles  : {orphan_pct:>20.2f}%")
            if orphan_pct > 5.0:
                print(f"    -  WARNING: >5% orphan rate. Consider raising GRID_LEN or GRID_MAX_PRES.")
        print()

        # ---- NORMALIZATION STATS ----
        print("  NORMALIZATION STATISTICS (computed from training set)")
        print("  " + "-" * 106)
        for var_name in ["TEMP", "PSAL"]:
            if var_name in norm_stats:
                stats = norm_stats[var_name]
                print(f"    {var_name:<30} mean={stats['mean']:>10.4f}  std={stats['std']:>10.4f}")
        if "PRES" in norm_stats:
            print(f"    {'PRES':<30} grid_max={norm_stats['PRES']['grid_max']:>10.1f} dbar")
        print()

        # ---- TEMPORAL COVERAGE ----
        print(" TEMPORAL COVERAGE")
        print("  " + "-" * 106)
        print(f"    Date range                         : {self.temporal_stats['date_range_min']} → {self.temporal_stats['date_range_max']}")
        print(f"    Years included                     : {', '.join(map(str, self.temporal_stats['years_included']))}")
        print(f"    Months covered                     : {self.temporal_stats['months_covered']:>20}/12")
        print()

        # ---- OUTPUT ----
        print("  OUTPUT DIRECTORY & FILES")
        print("  " + "-" * 106)
        print(f"    Location                           : {output_dir}")
        print(f"    Files saved                        : train/val/test (X_temp, X_psal, mask, qc_*, meta)")
        print(f"    Normalization config               : norm_stats.json")
        print(f"    QC reference                       : qc_reference.json")
        print()
        print("╚" + "=" * 108 + "╝")


def cast_qc_columns(chunk: pd.DataFrame) -> pd.DataFrame:
    """Cast QC flags to consistent types for filtering and comparison."""
    for col in OBS_QC_COLS:
        if col in chunk.columns:
            chunk[col] = chunk[col].astype("Int8")
    for col in PROFILE_QC_COLS:
        if col in chunk.columns:
            chunk[col] = chunk[col].astype(str).replace("nan", pd.NA)
    return chunk


class GlobalDiag:
    """Accumulate filtering statistics across all chunks."""

    def __init__(self):
        self.n_raw = 0
        self.qc_value_counts = {col: defaultdict(int)
                                 for col in ["JULD_QC", "TEMP_QC", "PSAL_QC", "PRES_QC", "POSITION_QC"]}
        self.direction_counts = defaultdict(int)
        self.dmode_counts = defaultdict(int)
        self.steps = {
            "start":              0,
            "juld_qc_filter":     0,
            "obs_qc_filter":      0,
            "position_qc_filter": 0,
            "dropna":             0,
            "direction_filter":   0,
            "datamode_d_filter":  0,
        }

    def update(self, chunk_raw: pd.DataFrame, filter_juld_qc: bool, ascending_only: bool,
               delayed_mode_only: bool = True, position_qc_filter: bool = True):
        chunk = cast_qc_columns(chunk_raw.copy())
        n0 = len(chunk)
        self.n_raw += n0
        self.steps["start"] += n0

        for col in ["JULD_QC", "TEMP_QC", "PSAL_QC", "PRES_QC", "POSITION_QC"]:
            if col in chunk.columns:
                vc = chunk[col].value_counts(dropna=False)
                for val, cnt in vc.items():
                    self.qc_value_counts[col][val] += int(cnt)

        if "DIRECTION" in chunk.columns:
            vc = chunk["DIRECTION"].value_counts(dropna=False)
            for val, cnt in vc.items():
                self.direction_counts[val] += int(cnt)

        if "DATA_MODE" in chunk.columns:
            vc = chunk["DATA_MODE"].value_counts(dropna=False)
            for val, cnt in vc.items():
                self.dmode_counts[val] += int(cnt)

        remaining = chunk
        if filter_juld_qc:
            remaining = remaining[remaining["JULD_QC"].isin(VALID_JULD_QC)]
        self.steps["juld_qc_filter"] += len(remaining)

        remaining = remaining[
            remaining["TEMP_QC"].isin(VALID_OBS_QC) &
            remaining["PSAL_QC"].isin(VALID_OBS_QC) &
            remaining["PRES_QC"].isin(VALID_OBS_QC)
        ]
        self.steps["obs_qc_filter"] += len(remaining)

        if position_qc_filter and "POSITION_QC" in remaining.columns:
            remaining = remaining[remaining["POSITION_QC"].isin(VALID_POSITION_QC)]
        self.steps["position_qc_filter"] += len(remaining)

        remaining = remaining.dropna(subset=["JULD", "PRES", "TEMP", "PSAL", "LATITUDE", "LONGITUDE"])
        self.steps["dropna"] += len(remaining)

        if ascending_only:
            remaining = remaining[remaining["DIRECTION"] == "A"]
        self.steps["direction_filter"] += len(remaining)

        if delayed_mode_only and "DATA_MODE" in remaining.columns:
            remaining = remaining[remaining["DATA_MODE"] == "D"]
        self.steps["datamode_d_filter"] += len(remaining)

    def report(self, delayed_mode_only: bool = True, position_qc_filter: bool = True):
        n = self.n_raw
        print()
        print("=" * 90)
        print(f"  GLOBAL FILTER DIAGNOSTICS ({n:,} raw rows)")
        print("=" * 90)

        print("\n  DATA_MODE distribution:")
        for val, cnt in self.dmode_counts.items():
            marker = " <- KEPT" if (not delayed_mode_only or val == "D") else " <- DISCARDED"
            pct = cnt / n * 100 if n else 0
            print(f"    {str(val):>6}  {cnt:>12,}  ({pct:5.1f}%){marker}")

        prev = n
        steps_to_show = [
            ("start",              "start"),
            ("JULD_QC filter",     "juld_qc_filter"),
            ("obs QC filter (T+S+P)", "obs_qc_filter"),
        ]
        if position_qc_filter:
            steps_to_show.append(("POSITION_QC filter (1/2)", "position_qc_filter"))
        steps_to_show.append(("dropna", "dropna"))
        steps_to_show.append(("DIRECTION == A", "direction_filter"))
        if delayed_mode_only:
            steps_to_show.append(("DATA_MODE == D", "datamode_d_filter"))

        print()
        for label, key in steps_to_show:
            cur = self.steps[key]
            pct = cur / n * 100 if n else 0
            print(f"    {label:28s}  {cur:>12,}  ({pct:5.1f}%)  dropped {prev - cur:,}")
            prev = cur
        print(f"\n  → Rows surviving all filters: {prev:,} / {n:,} ({prev / n * 100:.1f}%)")
        print("=" * 90)


def interp_profile(P: np.ndarray, T: np.ndarray, S: np.ndarray, grid: np.ndarray):
    """Interpolate TEMP and PSAL of a profile over fixed pressure grid.
    Returns None only if the profile has fewer than MIN_LEVELS raw points.
    Coverage is computed and returned but NOT used to discard here unless
    the caller explicitly checks DISCARD_LOW_COVERAGE."""
    order = np.argsort(P)
    P, T, S = P[order], T[order], S[order]

    uP, inv = np.unique(P, return_inverse=True)
    if len(uP) < len(P):
        T = np.bincount(inv, weights=T) / np.bincount(inv)
        S = np.bincount(inv, weights=S) / np.bincount(inv)
        P = uP

    if len(P) < MIN_LEVELS:
        return None

    T_i = np.interp(grid, P, T, left=np.nan, right=np.nan)
    S_i = np.interp(grid, P, S, left=np.nan, right=np.nan)
    mask = ~np.isnan(T_i)

    coverage = float(mask.mean())

    T_i = np.nan_to_num(T_i, nan=0.0).astype(np.float32)
    S_i = np.nan_to_num(S_i, nan=0.0).astype(np.float32)
    return T_i, S_i, mask, coverage


def compute_grid_qc(P: np.ndarray, QC_T: np.ndarray, QC_S: np.ndarray, QC_P: np.ndarray, grid: np.ndarray):
    """For each grid cell, assign the WORST (max) observation-level QC flag."""
    if len(grid) > 1:
        half_left  = np.diff(grid) / 2.0
        half_left  = np.concatenate([[half_left[0]], half_left])
        half_right = np.diff(grid) / 2.0
        half_right = np.concatenate([half_right, [half_right[-1]]])
        edges = np.concatenate([[grid[0] - half_left[0]], grid[:-1] + np.diff(grid) / 2.0, [grid[-1] + half_right[-1]]])
    else:
        edges = np.array([grid[0] - 1.0, grid[0] + 1.0])

    idx = np.searchsorted(edges, P, side="right") - 1
    idx = np.clip(idx, 0, len(grid) - 1)

    out_T = np.zeros(len(grid), dtype=np.int8)
    out_S = np.zeros(len(grid), dtype=np.int8)
    out_P = np.zeros(len(grid), dtype=np.int8)
    np.maximum.at(out_T, idx, QC_T.astype(np.int8))
    np.maximum.at(out_S, idx, QC_S.astype(np.int8))
    np.maximum.at(out_P, idx, QC_P.astype(np.int8))
    return out_T, out_S, out_P


def load_and_accumulate(parquet_path: str, ascending_only: bool, filter_juld_qc: bool,
                         delayed_mode_only: bool = True, position_qc_filter: bool = True):
    print("-" * 90)
    print("LOADING AND CLEANING (by chunks)")
    print("-" * 90)

    pf = pq.ParquetFile(parquet_path)

    available_cols = pq.read_schema(parquet_path).names
    cols_to_read   = [c for c in VARS_INTERES if c in available_cols]
    missing        = set(VARS_INTERES) - set(cols_to_read)
    if missing:
        print("\n  [WARNING] Columns not found in the parquet:")
        for m in sorted(missing):
            print(f"         - {m}")

    missing_required = set(REQUIRED_COLS) - set(cols_to_read)
    assert not missing_required, f"Missing required columns: {missing_required}"

    if delayed_mode_only and "DATA_MODE" not in cols_to_read:
        raise ValueError(
            "DELAYED_MODE_ONLY=True but 'DATA_MODE' column is not available in the parquet."
        )

    meta      = pq.read_metadata(parquet_path)
    total_raw = meta.num_rows
    print(f"\n  Raw observations in the parquet : {total_raw:,}\n")

    diag = GlobalDiag()

    # Row-level filter counters, printed the same way as the tabular preprocess
    filter_stats = {
        "n_raw":             0,
        "after_juld":        0,
        "after_obs_qc":      0,
        "after_position_qc": 0,
        "after_dropna":      0,
        "after_dir":         0,
        "after_dmode":       0,
    }

    stats = defaultdict(lambda: {
        "T_vals": [], "S_vals": [], "P_vals": [], "JULD_ns": [],
        "LAT_vals": [], "LON_vals": [],
        "TQC_vals": [], "SQC_vals": [], "PQC_vals": [],
        "T_bad": 0, "S_bad": 0, "P_bad": 0,
        "PROFILE_TEMP_QC": None, "PROFILE_PSAL_QC": None, "PROFILE_PRES_QC": None,
    })
    total_rows_read   = 0
    rows_after_filter = 0

    for i, batch in enumerate(pf.iter_batches(batch_size=CHUNK_SIZE, columns=cols_to_read)):
        chunk = batch.to_pandas()
        n_raw = len(chunk)
        total_rows_read += n_raw
        filter_stats["n_raw"] += n_raw

        diag.update(chunk.copy(), filter_juld_qc, ascending_only, delayed_mode_only, position_qc_filter)

        chunk = cast_qc_columns(chunk)

        if filter_juld_qc:
            chunk = chunk[chunk["JULD_QC"].isin(VALID_JULD_QC)]
        filter_stats["after_juld"] += len(chunk)

        chunk = chunk[
            chunk["TEMP_QC"].isin(VALID_OBS_QC) &
            chunk["PSAL_QC"].isin(VALID_OBS_QC) &
            chunk["PRES_QC"].isin(VALID_OBS_QC)
        ]
        filter_stats["after_obs_qc"] += len(chunk)

        if position_qc_filter and "POSITION_QC" in chunk.columns:
            chunk = chunk[chunk["POSITION_QC"].isin(VALID_POSITION_QC)]
        filter_stats["after_position_qc"] += len(chunk)

        for col in ["JULD", "PRES", "TEMP", "PSAL", "LATITUDE", "LONGITUDE"]:
            if col in chunk.columns:
                chunk = chunk[chunk[col].notna()]
        filter_stats["after_dropna"] += len(chunk)

        if ascending_only:
            chunk = chunk[chunk["DIRECTION"] == "A"]
        filter_stats["after_dir"] += len(chunk)

        if delayed_mode_only and "DATA_MODE" in chunk.columns:
            chunk = chunk[chunk["DATA_MODE"] == "D"]
        filter_stats["after_dmode"] += len(chunk)

        if chunk.empty:
            del chunk
            gc.collect()
            continue

        rows_after_filter += len(chunk)
        chunk.sort_values(PROFILE_KEY + ["PRES"], inplace=True)

        for (plat, cyc, direc), grp in chunk.groupby(PROFILE_KEY, sort=False):
            key = (plat, cyc, direc)
            s   = stats[key]
            s["T_vals"].append(grp["TEMP"].values.astype(np.float32))
            s["S_vals"].append(grp["PSAL"].values.astype(np.float32))
            s["P_vals"].append(grp["PRES"].values.astype(np.float32))
            s["JULD_ns"].append(grp[DATE_COL].values.astype("datetime64[ns]").astype(np.int64))
            s["LAT_vals"].append(grp["LATITUDE"].values.astype(np.float32))
            s["LON_vals"].append(grp["LONGITUDE"].values.astype(np.float32))
            s["TQC_vals"].append(grp["TEMP_QC"].values.astype(np.int8))
            s["SQC_vals"].append(grp["PSAL_QC"].values.astype(np.int8))
            s["PQC_vals"].append(grp["PRES_QC"].values.astype(np.int8))
            if not s["T_bad"] and grp["TEMP_QC"].isin([3, 4]).any():
                s["T_bad"] = 1
            if not s["S_bad"] and grp["PSAL_QC"].isin([3, 4]).any():
                s["S_bad"] = 1
            if not s["P_bad"] and grp["PRES_QC"].isin([3, 4]).any():
                s["P_bad"] = 1
            if s["PROFILE_TEMP_QC"] is None:
                s["PROFILE_TEMP_QC"] = grp["PROFILE_TEMP_QC"].iloc[0]
            if s["PROFILE_PSAL_QC"] is None:
                s["PROFILE_PSAL_QC"] = grp["PROFILE_PSAL_QC"].iloc[0]
            if s["PROFILE_PRES_QC"] is None:
                s["PROFILE_PRES_QC"] = grp["PROFILE_PRES_QC"].iloc[0]
        del chunk
        gc.collect()
        print(f"  Chunk {i + 1:3d} — {total_rows_read:>12,} raw | {rows_after_filter:>12,} kept")

    n = filter_stats["n_raw"]
    print()
    print("-" * 90)
    print("  ROW-LEVEL FILTER SUMMARY")
    print("-" * 90)
    steps = [
        ("Raw rows",                    filter_stats["n_raw"]),
        ("After JULD_QC filter",        filter_stats["after_juld"]        if filter_juld_qc else filter_stats["n_raw"]),
        ("After obs QC filter",         filter_stats["after_obs_qc"]),
        ("After POSITION_QC filter",    filter_stats["after_position_qc"] if position_qc_filter else filter_stats["after_obs_qc"]),
        ("After dropna",                filter_stats["after_dropna"]),
        ("After direction filter",      filter_stats["after_dir"]         if ascending_only else filter_stats["after_dropna"]),
        ("After DATA_MODE=D filter",    filter_stats["after_dmode"]       if delayed_mode_only else filter_stats["after_dir"]),
    ]
    prev = n
    for label, count in steps:
        dropped     = prev - count
        pct_kept    = count / n * 100 if n else 0
        pct_dropped = dropped / prev * 100 if prev > 0 else 0
        print(f"  {label:35s}  {count:>12,}  ({pct_kept:5.1f}% of total)  "
              f"[-{dropped:,} = -{pct_dropped:.1f}% of previous step]")
        prev = count
    print("-" * 90)

    diag.report(delayed_mode_only, position_qc_filter)

    print(f"\n  Unique keys (float, cycle, direction) : {len(stats):,}\n")

    return stats, total_raw, rows_after_filter


def build_profile_sequences(stats: dict):
    print()
    print("-" * 90)
    print("FIXED-GRID INTERPOLATION AND SEQUENCE CONSTRUCTION")
    print("-" * 90)

    n_candidate_profiles = len(stats)

    X_temp, X_psal, X_mask = [], [], []
    X_qc_temp, X_qc_psal, X_qc_pres = [], [], []
    meta_rows = []
    skipped_min_levels   = 0   # < MIN_LEVELS raw points -> always discarded
    skipped_low_coverage = 0   # only counted as discard if DISCARD_LOW_COVERAGE=True
    orphan_bad_profiles  = 0

    for key, s in stats.items():
        T = np.concatenate(s["T_vals"])
        S = np.concatenate(s["S_vals"])
        P = np.concatenate(s["P_vals"])
        J = np.concatenate(s["JULD_ns"])
        LAT = np.concatenate(s["LAT_vals"])
        LON = np.concatenate(s["LON_vals"])
        TQC = np.concatenate(s["TQC_vals"])
        SQC = np.concatenate(s["SQC_vals"])
        PQC = np.concatenate(s["PQC_vals"])

        result = interp_profile(P, T, S, PRESSURE_GRID)
        if result is None:
            skipped_min_levels += 1
            continue
        T_i, S_i, mask, coverage = result

        if coverage < MIN_COVERAGE:
            if DISCARD_LOW_COVERAGE:
                skipped_low_coverage += 1
                continue
            # else: keep the profile, rely on `mask` downstream (masked loss)

        qc_t_grid, qc_s_grid, qc_p_grid = compute_grid_qc(P, TQC, SQC, PQC, PRESSURE_GRID)

        X_temp.append(T_i)
        X_psal.append(S_i)
        X_mask.append(mask)
        X_qc_temp.append(qc_t_grid)
        X_qc_psal.append(qc_s_grid)
        X_qc_pres.append(qc_p_grid)

        is_bad = int(s["T_bad"] or s["S_bad"] or s["P_bad"])

        if is_bad and not (
            (qc_t_grid >= 3).any() or (qc_s_grid >= 3).any() or (qc_p_grid >= 3).any()
        ):
            orphan_bad_profiles += 1

        meta_rows.append({
            "PLATFORM_NUMBER": key[0], "CYCLE_NUMBER": key[1], "DIRECTION": key[2],
            "LATITUDE": float(LAT.mean()), "LONGITUDE": float(LON.mean()),
            "n_levels_raw": int(len(P)), "coverage_frac": coverage,
            "low_coverage": bool(coverage < MIN_COVERAGE),
            "TEMP_is_bad": s["T_bad"], "PSAL_is_bad": s["S_bad"], "PRES_is_bad": s["P_bad"],
            "is_bad": is_bad,
            "JULD_ns": int(J[0]),
            "PROFILE_TEMP_QC": s["PROFILE_TEMP_QC"],
            "PROFILE_PSAL_QC": s["PROFILE_PSAL_QC"],
            "PROFILE_PRES_QC": s["PROFILE_PRES_QC"],
            "max_pres_raw": float(P.max()),
        })

    X_temp = np.stack(X_temp).astype(np.float32)
    X_psal = np.stack(X_psal).astype(np.float32)
    X_mask = np.stack(X_mask).astype(bool)
    X_qc_temp = np.stack(X_qc_temp).astype(np.int8)
    X_qc_psal = np.stack(X_qc_psal).astype(np.int8)
    X_qc_pres = np.stack(X_qc_pres).astype(np.int8)
    df_meta = pd.DataFrame(meta_rows)
    df_meta["date"] = pd.to_datetime(df_meta["JULD_ns"].astype(np.int64), unit="ns")

    n_low_cov_kept = int(df_meta["low_coverage"].sum()) if len(df_meta) else 0

    print()
    print("  PROFILE-LEVEL FILTER SUMMARY")
    print(f"    Candidate profiles (unique float/cycle/direction) : {n_candidate_profiles:,}")
    print(f"    Discarded (< {MIN_LEVELS} raw levels)              : {skipped_min_levels:,}")
    print(f"    Discard low-coverage filter (DISCARD_LOW_COVERAGE) : {DISCARD_LOW_COVERAGE}")
    if DISCARD_LOW_COVERAGE:
        print(f"    Discarded (coverage < {MIN_COVERAGE:.0%})              : {skipped_low_coverage:,}")
    else:
        print(f"    Coverage < {MIN_COVERAGE:.0%} but KEPT (masked, not discarded) : {n_low_cov_kept:,} "
              f"({n_low_cov_kept / max(len(df_meta), 1):.2%} of valid profiles)")
    print(f"    Valid profiles                                    : {len(df_meta):,}")
    print(f"    Shape X_temp / X_psal / X_mask                    : {X_temp.shape}")
    print(f"    Anomalous profiles                                : {df_meta['is_bad'].sum():,} ({df_meta['is_bad'].mean():.2%})")
    print(f"    Average coverage per profile                      : {df_meta['coverage_frac'].mean():.2%}")
    print(f"    Date range                                        : {df_meta['date'].min().date()} → {df_meta['date'].max().date()}")

    print()
    print("  [DIAGNOSTIC] Grid coverage / zero-filled points")
    frac_zero = 1.0 - X_mask.mean()
    print(f"    Overall zero-filled (profile, level) cells : {frac_zero:.2%}")
    cov_per_level = X_mask.mean(axis=0)
    worst_idx = np.argsort(cov_per_level)[:10]
    print("    10 worst-covered grid levels (pressure dbar → fraction covered):")
    worst_levels = {}
    for lvl in worst_idx:
        pres = PRESSURE_GRID[lvl]
        cov = cov_per_level[lvl]
        print(f"      {pres:7.1f} dbar → {cov:.2%}")
        worst_levels[f"{pres:.1f}"] = float(cov)

    n_bad = int(df_meta["is_bad"].sum())
    print()
    print("  [DIAGNOSTIC] Orphan bad profiles (grid QC loses the bad flag)")
    print(f"    is_bad profiles total                      : {n_bad:,}")
    print(f"    ...of those, with NO QC 3/4 anywhere on grid: {orphan_bad_profiles:,} ({orphan_bad_profiles / max(n_bad, 1):.2%})")
    beyond_grid = int((df_meta["is_bad"] & (df_meta["max_pres_raw"] > GRID_MAX_PRES)).sum())
    print(f"    ...likely due to profiles deeper than GRID_MAX_PRES: {beyond_grid:,}")
    if orphan_bad_profiles / max(n_bad, 1) > 0.05:
        print("     WARNING: More than 5% of bad profiles have no visible bad grid cell.")
        print("       → Consider raising GRID_LEN (keep multiple of 4) and/or GRID_MAX_PRES.")

    return (X_temp, X_psal, X_mask, X_qc_temp, X_qc_psal, X_qc_pres, df_meta,
            worst_levels, orphan_bad_profiles, skipped_min_levels, skipped_low_coverage, n_low_cov_kept)


def split_temporal_idx(df_meta):
    print()
    print("-" * 90)
    print("TEMPORAL SPLIT")
    print("-" * 90)

    train_mask = df_meta["date"] < TRAIN_END
    val_mask   = (df_meta["date"] >= TRAIN_END) & (df_meta["date"] < VAL_END)
    test_mask  = df_meta["date"] >= VAL_END

    if not (train_mask.any() and val_mask.any() and test_mask.any()):
        raise ValueError("One of the splits ended up empty, check TRAIN_END/VAL_END against the date range.")

    for name, mask in [("train", train_mask), ("val", val_mask), ("test", test_mask)]:
        sub = df_meta.loc[mask]
        print(f"  {name:6s} : {mask.sum():>7,} profiles | "
              f"{sub['date'].min().date()} → {sub['date'].max().date()} | "
              f"{sub['is_bad'].mean():.2%} anomalous | "
              f"{sub['PLATFORM_NUMBER'].nunique():,} unique floats")

    return train_mask.values, val_mask.values, test_mask.values


def split_platform_idx(df_meta, seed=42):
    print()
    print("-" * 90)
    print("SPLIT BY FLOAT (Platform-based)")
    print("-" * 90)

    platforms = df_meta["PLATFORM_NUMBER"].unique()
    rng = np.random.default_rng(seed)
    rng.shuffle(platforms)

    n       = len(platforms)
    n_train = int(n * 0.70)
    n_val   = int(n * 0.15)

    train_plats = set(platforms[:n_train])
    val_plats   = set(platforms[n_train: n_train + n_val])
    test_plats  = set(platforms[n_train + n_val:])

    train_mask = df_meta["PLATFORM_NUMBER"].isin(train_plats).values
    val_mask   = df_meta["PLATFORM_NUMBER"].isin(val_plats).values
    test_mask  = df_meta["PLATFORM_NUMBER"].isin(test_plats).values

    assert not (train_plats & val_plats)
    assert not (train_plats & test_plats)

    for name, mask in [("train", train_mask), ("val", val_mask), ("test", test_mask)]:
        sub = df_meta.loc[mask]
        print(f"  {name:6s} : {mask.sum():>7,} profiles | {sub['is_bad'].mean():.2%} anomalous")

    return train_mask, val_mask, test_mask


def save_split(output_dir, name, X_temp, X_psal, X_mask, X_qc_temp, X_qc_psal, X_qc_pres, df_meta, mask_idx):
    os.makedirs(output_dir, exist_ok=True)
    np.save(os.path.join(output_dir, f"{name}_X_temp.npy"), X_temp[mask_idx])
    np.save(os.path.join(output_dir, f"{name}_X_psal.npy"), X_psal[mask_idx])
    np.save(os.path.join(output_dir, f"{name}_mask.npy"),   X_mask[mask_idx])
    np.save(os.path.join(output_dir, f"{name}_qc_temp_grid.npy"), X_qc_temp[mask_idx])
    np.save(os.path.join(output_dir, f"{name}_qc_psal_grid.npy"), X_qc_psal[mask_idx])
    np.save(os.path.join(output_dir, f"{name}_qc_pres_grid.npy"), X_qc_pres[mask_idx])
    meta_split = df_meta.loc[mask_idx].reset_index(drop=True)
    meta_split.to_parquet(os.path.join(output_dir, f"{name}_meta.parquet"),
                           index=False, compression="snappy")
    print(f"  {name:5s} saved → {len(meta_split):,} profiles | {meta_split['is_bad'].mean() * 100:.2f}% anomalous")


def run_pipeline(ocean_name: str, parquet_path: str, output_base: str):
    """Runs the full load -> grid -> split -> save pipeline for one ocean."""

    output_dir = os.path.join(output_base, f"split_{SPLIT_MODE}_{desc_tag}{dmode_tag}{cov_tag}_grid{GRID_LEN}")

    print()
    print("#" * 90)
    print(f"#  OCEAN: {ocean_name.upper()}")
    print(f"#  Parquet: {parquet_path}")
    print(f"#  Output : {output_dir}")
    print("#" * 90)

    print(f"  Configuration:")
    print(f"    Split mode            : {SPLIT_MODE}")
    print(f"    Ascending only        : {ASCENDING_ONLY}")
    print(f"    Delayed mode only     : {DELAYED_MODE_ONLY}")
    print(f"    Position QC filter    : {POSITION_QC_FILTER}")
    print(f"    Grid resolution       : {GRID_LEN} levels, 0–{GRID_MAX_PRES} dbar")
    print(f"    Min coverage          : {MIN_COVERAGE:.0%}")
    print(f"    Discard low coverage  : {DISCARD_LOW_COVERAGE}")
    print(f"    Output directory      : {output_dir}")
    print()

    # Load and clean
    stats, total_raw, total_clean = load_and_accumulate(
        parquet_path=parquet_path,
        ascending_only=ASCENDING_ONLY,
        filter_juld_qc=filter_juld_qc,
        delayed_mode_only=DELAYED_MODE_ONLY,
        position_qc_filter=POSITION_QC_FILTER,
    )

    # Build sequences
    (X_temp, X_psal, X_mask, X_qc_temp, X_qc_psal, X_qc_pres, df_meta,
     worst_levels, orphan_bad, skipped_min_levels, skipped_low_coverage,
     n_low_cov_kept) = build_profile_sequences(stats)
    del stats
    gc.collect()

    # Month coverage analysis
    print()
    print("=" * 90)
    print("MONTH COVERAGE ANALYSIS (all splits combined)")
    print("=" * 90)
    df_meta["month"] = pd.to_datetime(df_meta["date"]).dt.month
    df_meta["year"] = pd.to_datetime(df_meta["date"]).dt.year

    month_counts = df_meta["month"].value_counts().sort_index()
    all_months = set(range(1, 13))
    covered_months = set(month_counts.index.tolist())
    missing_months = sorted(all_months - covered_months)

    print(f"\nMonths covered: {sorted(covered_months)} ({len(covered_months)}/12)")
    if missing_months:
        print(f"Months MISSING:  {missing_months}")
    else:
        print("- ALL 12 months covered!")

    print("\nProfiles per month:")
    for m in range(1, 13):
        count = month_counts.get(m, 0)
        pct = (count / len(df_meta) * 100) if len(df_meta) > 0 else 0
        status = "✓" if count > 0 else "X"
        print(f"  {status} Month {m:2d}: {count:>7,} profiles ({pct:5.1f}%)")

    print()
    print("=" * 90)

    # Split data
    if SPLIT_MODE == "time":
        train_idx, val_idx, test_idx = split_temporal_idx(df_meta)
    else:
        train_idx, val_idx, test_idx = split_platform_idx(df_meta)

    os.makedirs(output_dir, exist_ok=True)
    np.save(os.path.join(output_dir, "pressure_grid.npy"), PRESSURE_GRID)

    # Save splits
    print()
    print("-" * 90)
    print("SAVING OUTPUTS")
    print("-" * 90)
    save_split(output_dir, "train", X_temp, X_psal, X_mask, X_qc_temp, X_qc_psal, X_qc_pres, df_meta, train_idx)
    save_split(output_dir, "val",   X_temp, X_psal, X_mask, X_qc_temp, X_qc_psal, X_qc_pres, df_meta, val_idx)
    save_split(output_dir, "test",  X_temp, X_psal, X_mask, X_qc_temp, X_qc_psal, X_qc_pres, df_meta, test_idx)

    # Also save the full profile-level metadata table (not just per split) so
    # a separate comparison script can check overlap with the tabular pipeline.
    df_meta.to_parquet(os.path.join(output_dir, "profiles_meta_full.parquet"), index=False, compression="snappy")

    # Compute normalization stats
    norm_stats = {}
    for name, X in [("TEMP", X_temp), ("PSAL", X_psal)]:
        train_vals = X[train_idx][X_mask[train_idx]]
        norm_stats[name] = {
            "mean": float(train_vals.mean()),
            "std":  float(train_vals.std() + 1e-8),
        }

    norm_stats["PRES"] = {"grid_max": float(GRID_MAX_PRES)}

    norm_path = os.path.join(output_dir, "norm_stats.json")
    with open(norm_path, "w") as f:
        json.dump(norm_stats, f, indent=2)

    qc_ref_path = os.path.join(output_dir, "qc_reference.json")
    with open(qc_ref_path, "w") as f:
        json.dump(QC_LETTER_DESC, f, indent=2)

    print(f"  norm_stats.json     → {norm_path}")
    print(f"  qc_reference.json   → {qc_ref_path}")

    # Generate comprehensive final report
    report = FinalReport()
    report.total_raw = total_raw
    report.total_cleaned = total_clean
    report.n_valid_profiles = len(df_meta)

    for split_name, split_idx in [("train", train_idx), ("val", val_idx), ("test", test_idx)]:
        split_data = df_meta.loc[split_idx]
        report.add_split_stats(
            split_name,
            n_profiles=len(split_data),
            n_anomalous=int(split_data["is_bad"].sum()),
            n_unique_floats=int(split_data["PLATFORM_NUMBER"].nunique()),
            date_min=str(split_data["date"].min().date()),
            date_max=str(split_data["date"].max().date()),
        )

    report.add_grid_stats(
        avg_coverage=float(df_meta["coverage_frac"].mean()),
        n_skipped=skipped_low_coverage,
        orphan_profiles=orphan_bad,
        worst_levels=worst_levels,
        n_low_coverage_kept=n_low_cov_kept,
        discard_low_coverage=DISCARD_LOW_COVERAGE,
    )

    report.add_temporal_stats(
        date_min=str(df_meta["date"].min().date()),
        date_max=str(df_meta["date"].max().date()),
        years=sorted(df_meta["year"].unique().tolist()),
        months_covered=len(covered_months),
    )

    report.print_comprehensive_report(output_dir, GRID_LEN, GRID_MAX_PRES, norm_stats)

    print()
    print(f"[{ocean_name.upper()}] Completed successfully at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print()

    del X_temp, X_psal, X_mask, X_qc_temp, X_qc_psal, X_qc_pres, df_meta
    gc.collect()


# MAIN EXECUTION

if __name__ == "__main__":

    results = {}
    for ocean_name, cfg in OCEAN_CONFIGS.items():
        try:
            run_pipeline(ocean_name, cfg["parquet_path"], cfg["output_base"])
            results[ocean_name] = "OK"
        except Exception as e:
            print(f"\n[ERROR] Pipeline failed for {ocean_name}: {e}\n")
            results[ocean_name] = f"FAILED: {e}"

    print()
    print("=" * 90)
    print("  RUN SUMMARY — ALL OCEANS")
    print("=" * 90)
    for ocean_name, status in results.items():
        print(f"    {ocean_name:12s} : {status}")
    print("=" * 90)