"""
Isolation Forest training for 3 oceans (Atlantic, Indian, Pacific)

-To run after: /.../preprocessing.ipynb

Load the splits generated by argo_preprocess.py for each ocean.
For each ocean:
  - Optimize F1-macro with HalvingRandomSearchCV (CV on train only)
  - Tune the threshold (score percentile) on val
  - Evaluate on test
  - Save everything in its own results folder and its own MLflow experiment

NOTE:
Isolation Forest is an UNSUPERVISED anomaly detector: it is fitted
on X (without using y) and produces a continuous anomaly score (higher =
more anomalous). To enable a seamless comparison with XGBoost/LightGBM
in this pipeline:

  - sklearn.ensemble.IsolationForest is wrapped in a custom class
    (IsolationForestF1) that exposes predict()/score() in the same
    0=Good / 1=Bad format used by the other scripts, allowing us to:
      * use HalvingRandomSearchCV with scoring="f1_macro" (compares
        predict() for each fold against the true labels)
      * perform threshold tuning on val just like with XGBoost/LightGBM,
        but sweeping PERCENTILES of the anomaly score (rather than a fixed
        0.05-0.95 grid, because IsolationForest scores are not bounded
        between 0 and 1 like probabilities)
"""

import os, gc, json, warnings
import numpy as np
import pandas as pd
import joblib
import mlflow
import mlflow.sklearn
from scipy.stats import randint, uniform
from sklearn.base import BaseEstimator, ClassifierMixin
from sklearn.ensemble import IsolationForest
from sklearn.experimental import enable_halving_search_cv
from sklearn.model_selection import HalvingRandomSearchCV, StratifiedKFold
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score,
    roc_curve,
    auc,
    roc_auc_score,
)

warnings.filterwarnings("ignore")

# SET UP PATHS
OCEANS = {
    "Atlantic": {
        "preprocess_dir": "/work/drgarcia/Dataset/atlantic_ocean/2021-2025/2.preprocessed/split_time_ascA_dmodeD",
        "model_dir":      "/work/drgarcia/Models_and_results/IsolationForest/2021_2025/atlantic_f1macro_time_asc_nounder",
        "color":          "#1f77b4",
    },
    "Indian": {
        "preprocess_dir": "/work/drgarcia/Dataset/indian_ocean/2021-2025/2.preprocessed/split_time_ascA_dmodeD",
        "model_dir":      "/work/drgarcia/Models_and_results/IsolationForest/2021_2025/indian_f1macro_time_asc_nounder",
        "color":          "#2ca02c",
    },
    "Pacific": {
        "preprocess_dir": "/work/drgarcia/Dataset/pacific_ocean/2021-2025/2.preprocessed/split_time_ascA_dmodeD",
        "model_dir":      "/work/drgarcia/Models_and_results/IsolationForest/2021_2025/pacific_f1macro_time_asc_nounder",
        "color":          "#ff7f0e",
    },
}

MLFLOW_DIR = "/home/drgarcia/Argo_ml_code/ML_flow"

# MLflow: a single shared tracking URI, but a separate EXPERIMENT
# per ocean (so each ocean is kept separate in the MLflow UI)
mlflow.set_tracking_uri(f"sqlite:///{MLFLOW_DIR}/mlflow.db")


# WRAPPER: IsolationForest -> "0=Good / 1=Bad" interface
class IsolationForestF1(BaseEstimator, ClassifierMixin):
    """
    Wraps sklearn.ensemble.IsolationForest so that:
  - fit(X, y) ignores y (UNSUPERVISED model) but accepts the signature
    required by HalvingRandomSearchCV / StratifiedKFold.
  - predict(X) returns 0/1 (Good/Bad) instead of 1/-1, allowing
    scoring="f1_macro" to be used directly.
  - anomaly_score(X) returns a continuous score where HIGHER =
    MORE ANOMALOUS (more "Bad"), consistent with predict_proba[:,1]
    from the other models.
    """
    def __init__(self, n_estimators=200, max_samples="auto", max_features=1.0,
                 bootstrap=False, contamination="auto", random_state=42, n_jobs=4):
        self.n_estimators   = n_estimators
        self.max_samples    = max_samples
        self.max_features   = max_features
        self.bootstrap      = bootstrap
        self.contamination  = contamination
        self.random_state   = random_state
        self.n_jobs         = n_jobs

    def fit(self, X, y=None):
        self.model_ = IsolationForest(
            n_estimators=self.n_estimators,
            max_samples=self.max_samples,
            max_features=self.max_features,
            bootstrap=self.bootstrap,
            contamination=self.contamination,
            random_state=self.random_state,
            n_jobs=self.n_jobs,
        )
        self.model_.fit(X)
        return self

    def anomaly_score(self, X):
        # score_samples: LOWER = more anomalous -> we invert the sign
        # so that HIGHER = more anomalous (more "Bad"), same as probs[:,1]
        return -self.model_.score_samples(X)

    def predict(self, X):
        # Native IsolationForest predict: -1 = anomaly, 1 = normal
        raw = self.model_.predict(X)
        return np.where(raw == -1, 1, 0)  # 1=Bad, 0=Good

    def predict_at_threshold(self, X, threshold):
        return (self.anomaly_score(X) >= threshold).astype(int)


def _load_split(preprocess_dir, feature_cols, name):
    df = pd.read_parquet(os.path.join(preprocess_dir, f"{name}.parquet"))
    X  = df[feature_cols].astype(np.float32)
    y  = df["is_bad"]
    return X, y


def train_one_ocean(ocean_name, cfg):
    preprocess_dir = cfg["preprocess_dir"]
    output_dir     = cfg["model_dir"]
    os.makedirs(output_dir, exist_ok=True)

    print("\n" + "#" * 70)
    print(f"#   OCEAN: {ocean_name}")
    print("#" * 70)

    # LOAD PREPROCESSED SPLITS
    feature_cols = joblib.load(os.path.join(preprocess_dir, "feature_cols.pkl"))

    X_train, y_train = _load_split(preprocess_dir, feature_cols, "train")
    X_val,   y_val   = _load_split(preprocess_dir, feature_cols, "val")
    X_test,  y_test  = _load_split(preprocess_dir, feature_cols, "test")
    df_test_meta      = pd.read_parquet(os.path.join(preprocess_dir, "test_meta.parquet"))

    n_good          = (y_train == 0).sum()
    n_bad           = (y_train == 1).sum()
    imbalance_ratio = n_good / n_bad
    train_bad_frac  = float(y_train.mean())  # ~ expected contamination

    print(f"  Train : {len(X_train):,} profiles | {y_train.mean():.2%} anomalous")
    print(f"  Val   : {len(X_val):,}   profiles | {y_val.mean():.2%} anomalous")
    print(f"  Test  : {len(X_test):,}  profiles | {y_test.mean():.2%} anomalous")
    print(f"  Features: {len(feature_cols)}  →  {feature_cols}")
    print(f"  Train bad fraction (~contamination): {train_bad_frac:.4f}")

    # IsolationForest requires contamination in (0.0, 0.5]. When the "bad" class
    # is the majority (as in Pacific), train_bad_frac can exceed 0.5 and blow up
    # .fit(). Clip it to a safe range before using it as contamination anywhere.
    baseline_contamination = float(np.clip(train_bad_frac, 1e-4, 0.5))
    if train_bad_frac > 0.5:
        print(f"  [WARNING] train_bad_frac={train_bad_frac:.4f} > 0.5 "
              f"(majority class is 'bad') — clipping contamination to "
              f"{baseline_contamination:.4f} for the baseline model")

    # MLFLOW SETUP — dedicated experiment per ocean
    experiment_name = f"IsolationForest_{ocean_name}_TemporalSplit"
    experiment      = mlflow.get_experiment_by_name(experiment_name)
    if experiment is None:
        experiment_id = mlflow.create_experiment(
            name=experiment_name,
            artifact_location=f"file://{MLFLOW_DIR}/mlruns",
        )
        print(f"\nExperiment '{experiment_name}' created (id={experiment_id})")
    else:
        experiment_id = experiment.experiment_id
        print(f"\nUsing experiment '{experiment_name}' (id={experiment_id})")

    mlflow.set_experiment(experiment_name)

    # TRAINING
    with mlflow.start_run(run_name=f"IsolationForest_2021_2025_f1_time_ascD_nounder_Dmode_minlvls10_{ocean_name.lower()}"):

        mlflow.log_params({
            "ocean":           ocean_name,
            "split_type":      "time",
            "delayed_mode":    "only_d_mode",
            "Min_lvls":         "10",
            "direction":       "ascending_cycles_only",
            "undersample":     "false",
            "preprocess_dir":  preprocess_dir,
            "n_features":      len(feature_cols),
            "train_profiles":  len(X_train),
            "val_profiles":    len(X_val),
            "test_profiles":   len(X_test),
            "train_pct_bad":   train_bad_frac,
            "scoring":         "f1_macro",
            "imbalance_ratio": float(imbalance_ratio),
        })

        # BASELINE
        print("\n" + "=" * 70)
        print("Baseline Isolation Forest (200 trees, contamination=train_bad_frac)")
        print("=" * 70)

        if_base = IsolationForestF1(n_estimators=200, max_samples="auto", max_features=1.0,
        bootstrap=False, contamination=baseline_contamination,
        random_state=42, n_jobs=4,
        )
        # UNSUPERVISED fit: trained on full X_train (does not use y)
        if_base.fit(X_train)

        y_proba_base = if_base.anomaly_score(X_test)
        y_pred_base  = if_base.predict(X_test)  # uses the contamination set above
        baseline_auc = roc_auc_score(y_test, y_proba_base)
        baseline_f1  = f1_score(y_test, y_pred_base, average="macro")

        print(f"  Baseline ROC-AUC (test) : {baseline_auc:.4f}")
        print(f"  Baseline F1-macro (test): {baseline_f1:.4f}")
        mlflow.log_metrics({
            "baseline_roc_auc":  baseline_auc,
            "baseline_f1_macro": baseline_f1,
        })

        # HYPERPARAMETER SEARCH
        print("\n" + "=" * 70)
        print("HalvingRandomSearchCV — scoring=f1_macro  (CV on train only)")
        print("=" * 70)
        print("NOTE: IsolationForest fit() ignores y; scoring compares")
        print("      predict() (based on 'contamination') against true y.")

        # contamination must be in (0, 0.5]; we search around the
        # actual fraction of anomalies in train
        cont_low  = float(np.clip(train_bad_frac * 0.4, 1e-4, 0.5))
        cont_high = float(np.clip(train_bad_frac * 2.5, cont_low + 1e-4, 0.5))

        param_dist = {
            'n_estimators':    randint(100, 1000),
            'max_samples':     uniform(0.2, 0.8),     # fraction of X_train per tree
            'max_features':    uniform(0.5, 0.5),     # fraction of features per tree
            'bootstrap':       [True, False],
            'contamination':   uniform(cont_low, cont_high - cont_low),
        }

        cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

        if_tuned = IsolationForestF1(random_state=42, n_jobs=4)

        search = HalvingRandomSearchCV(
            estimator=if_tuned,
            param_distributions=param_dist,
            factor=3,
            n_candidates=40,
            min_resources="exhaust",
            cv=cv,
            scoring="f1_macro",      # F1-macro, same as XGBoost/LightGBM
            n_jobs=1,
            verbose=2,
            random_state=42,
        )

        print("\nStarting hyperparameter search...")
        search.fit(X_train, y_train)

        cv_results     = pd.DataFrame(search.cv_results_).sort_values("mean_test_score", ascending=False)
        best_if_model  = search.best_estimator_
        best_params    = search.best_params_

        print(f"\nBest F1-macro (CV on train): {search.best_score_:.4f}")
        mlflow.log_params(best_params)
        mlflow.log_metric("best_cv_f1_macro", search.best_score_)

        # THRESHOLD TUNING ON VAL (on anomaly_score percentiles)
        print("\n" + "=" * 70)
        print("Threshold tuning on validation set (anomaly score percentiles)")
        print("=" * 70)

        scores_val = best_if_model.anomaly_score(X_val)
        # sweep percentiles 5 to 95 of the score seen on val, instead of
        # a fixed 0.05-0.95 grid (the score is not bounded between 0 and 1)
        percentiles = np.arange(5, 96, 5)
        thresholds  = np.percentile(scores_val, percentiles)

        records = []
        for pct, t in zip(percentiles, thresholds):
            yp = (scores_val >= t).astype(int)
            tn, fp, fn, tp = confusion_matrix(y_val, yp, labels=[0, 1]).ravel()
            records.append({
                "threshold":      t,
                "percentile":     pct,
                "f1_macro":       f1_score(y_val, yp, average="macro",    zero_division=0),
                "f1_anomaly":     f1_score(y_val, yp, pos_label=1,         zero_division=0),
                "recall_anom":    recall_score(y_val, yp, pos_label=1,     zero_division=0),
                "precision_anom": precision_score(y_val, yp, pos_label=1,  zero_division=0),
                "tpr": tp / (tp + fn) if (tp + fn) > 0 else 0.0,
                "fpr": fp / (fp + tn) if (fp + tn) > 0 else 0.0,
            })

        df_th = pd.DataFrame(records)
        df_th["youden"] = df_th["tpr"] - df_th["fpr"]

        # Primary: best F1-macro on val
        high_recall_rows  = df_th[df_th["recall_anom"] >= 0.90].sort_values("precision_anom", ascending=False)
        best_recall90_row = high_recall_rows.iloc[0] if not high_recall_rows.empty \
                            else df_th.loc[df_th["recall_anom"].idxmax()]
        best_f1_macro_row = df_th.loc[df_th["f1_macro"].idxmax()]
        chosen_threshold  = float(best_f1_macro_row["threshold"])
        # USE THIS OPTION
        #chosen_threshold = float(best_recall90_row["threshold"])
        # Secondary candidates (logged, not used in final eval)
        best_f1_anom_row  = df_th.loc[df_th["f1_anomaly"].idxmax()]
        best_youden_row   = df_th.loc[df_th["youden"].idxmax()]

        print(f"  Best F1-macro   threshold (val): {chosen_threshold:.4f}  "
              f"(percentile {best_f1_macro_row['percentile']:.0f})  "
              f": f1_macro={best_f1_macro_row['f1_macro']:.4f}  "
              f"recall_anom={best_f1_macro_row['recall_anom']:.4f}")
        print(f"  Best F1-anomaly threshold (val): {best_f1_anom_row['threshold']:.4f}")
        print(f"  Best Youden     threshold (val): {best_youden_row['threshold']:.4f}")
        print(f"  Best recall≥90  threshold (val): {best_recall90_row['threshold']:.4f}")

        mlflow.log_metrics({
            "val_f1_macro_at_chosen":    float(best_f1_macro_row["f1_macro"]),
            "val_recall_anom_at_chosen": float(best_f1_macro_row["recall_anom"]),
            "val_precision_at_chosen":   float(best_f1_macro_row["precision_anom"]),
            "chosen_threshold":          chosen_threshold,
            "chosen_percentile":         float(best_f1_macro_row["percentile"]),
        })

        # FINAL EVALUATION ON TEST
        print("\n" + "=" * 70)
        print(f"Evaluation on TEST  (threshold={chosen_threshold:.4f} from val)")
        print("=" * 70)

        probs        = best_if_model.anomaly_score(X_test)
        y_pred_final = (probs >= chosen_threshold).astype(int)

        fpr_roc, tpr_roc, _ = roc_curve(y_test, probs)
        test_roc_auc         = auc(fpr_roc, tpr_roc)
        test_f1_macro        = f1_score(y_test, y_pred_final, average="macro")
        test_f1_anom         = f1_score(y_test, y_pred_final, pos_label=1, zero_division=0)
        test_recall_anom     = recall_score(y_test, y_pred_final, pos_label=1, zero_division=0)
        test_precision_anom  = precision_score(y_test, y_pred_final, pos_label=1, zero_division=0)

        mlflow.log_metrics({
            "test_roc_auc":        test_roc_auc,
            "test_f1_macro":       test_f1_macro,
            "test_f1_anomaly":     test_f1_anom,
            "test_recall_anomaly": test_recall_anom,
            "test_precision_anom": test_precision_anom,
        })

        print("\nBASELINE  (test, contamination=train_bad_frac)")
        print("=" * 70)
        print(classification_report(y_test, y_pred_base, target_names=["Good", "Bad"], digits=4))

        print(f"\nOPTIMIZED  (test, threshold={chosen_threshold:.4f} tuned on val, scoring=f1_macro)")
        print("=" * 70)
        print(classification_report(y_test, y_pred_final, target_names=["Good", "Bad"], digits=4))

        # SAVE ARTIFACTS
        print("\n" + "=" * 70)
        print("Saving artifacts")
        print("=" * 70)

        def _save(label, fn):
            try:
                fn()
                print(f"  - {label}")
            except Exception as e:
                print(f"  x {label}: {e}")

        _save("Model",
              lambda: joblib.dump(best_if_model,
                                  os.path.join(output_dir, "isoforest_optimized.pkl")))

        plot_bundle = {
            "ocean":               ocean_name,
            "color":               cfg["color"],
            "cv_results":          cv_results,
            "feature_cols":        feature_cols,
            "df_th":               df_th,
            "y_val":               y_val.values,
            "probs_val":           scores_val,   # anomaly score, not calibrated probability
            "y_test":              y_test.values,
            "probs":               probs,        # ditto
            "y_proba_base":        y_proba_base,
            "y_pred_base":         y_pred_base,
            "y_pred_final":        y_pred_final,
            "chosen_threshold":    chosen_threshold,
            "best_f1_macro_row":   best_f1_macro_row.to_dict(),
            "best_f1_anom_row":    best_f1_anom_row.to_dict(),
            "best_youden_row":     best_youden_row.to_dict(),
            "best_recall90_row":   best_recall90_row.to_dict(),
            "fpr_roc":             fpr_roc,
            "tpr_roc":             tpr_roc,
            "variables_qc": {
                "PRES": df_test_meta["PRES_is_bad"].values if "PRES_is_bad" in df_test_meta.columns else None,
                "TEMP": df_test_meta["TEMP_is_bad"].values if "TEMP_is_bad" in df_test_meta.columns else None,
                "PSAL": df_test_meta["PSAL_is_bad"].values if "PSAL_is_bad" in df_test_meta.columns else None,
            },
            "split_info": {
                "ocean":          ocean_name,
                "type":           "time",
                "direction":      "ascending_only",
                "undersample":    "false",
                "scoring":        "f1_macro",
                "preprocess_dir": preprocess_dir,
                "note":           "probs/probs_val are anomaly scores (not calibrated probabilities)",
            },
        }
        _save("Plot bundle",
              lambda: joblib.dump(plot_bundle, os.path.join(output_dir, "plot_data_bundle.pkl")))

        def _save_test_results():
            out = df_test_meta.copy()
            out["y_pred"]         = y_pred_final
            out["anomaly_score"]  = probs
            out.to_parquet(os.path.join(output_dir, "test_results.parquet"), index=False)
        _save("Test results parquet", _save_test_results)

        threshold_info = {
            "ocean":            ocean_name,
            "chosen_threshold": chosen_threshold,
            "chosen_by":        "f1_macro_val",
            "th_f1_macro":      float(best_f1_macro_row["threshold"]),
            "th_f1_anomaly":    float(best_f1_anom_row["threshold"]),
            "th_youden":        float(best_youden_row["threshold"]),
            "th_recall90":      float(best_recall90_row["threshold"]),
            "best_params":      best_params,
            "tuned_on":         "validation",
        }
        _save("Threshold info",
              lambda: joblib.dump(threshold_info,
                                  os.path.join(output_dir, "threshold_info.pkl")))

        def _save_json():
            d = {**{str(k): str(v) for k, v in best_params.items()}, **threshold_info}
            with open(os.path.join(output_dir, "best_params.json"), "w") as f:
                json.dump(d, f, indent=4)
        _save("Best params JSON", _save_json)

        _save("HP search CSV",
              lambda: cv_results.to_csv(
                  os.path.join(output_dir, "hyperparameter_search_results.csv"), index=False))

        _save("Threshold CSV",
              lambda: df_th.to_csv(
                  os.path.join(output_dir, "threshold_analysis.csv"), index=False))

        def _save_report():
            path = os.path.join(output_dir, "classification_report.txt")
            with open(path, "w") as f:
                f.write(f"Isolation Forest — {ocean_name} | Time split | Ascending only | Not undersampled | scoring=f1_macro \n")
                f.write("=" * 70 + "\n\n")
                f.write("BASELINE  (test, contamination=train_bad_frac)\n")
                f.write(classification_report(y_test, y_pred_base,
                                              target_names=["Good", "Bad"], digits=4))
                f.write(f"\n\nOPTIMIZED  (threshold={chosen_threshold:.4f}, tuned on val)\n")
                f.write(classification_report(y_test, y_pred_final,
                                              target_names=["Good", "Bad"], digits=4))
        _save("Classification report", _save_report)

        _save("MLflow model log",
              lambda: mlflow.sklearn.log_model(best_if_model, name="isoforest_optimized_model"))

    # free memory before the next ocean
    del X_train, y_train, X_val, y_val, X_test, y_test, df_test_meta
    gc.collect()


if __name__ == "__main__":
    for ocean_name, cfg in OCEANS.items():
        train_one_ocean(ocean_name, cfg)

    print("\n" + "#" * 70)
    print("#   Train completed for 3 oceans (Atlantic, Indian, Pacific)")